[Performance] Offscreen images
jetthoughts/jt.github.io pull request #271
Opened 2018-04-27 15:01 UTC by andriyParashchuk

Offscreen images are images that appear below the fold. Since users can't see offscreen images when they load a page, there's no reason to download the offscreen images as part of the initial page load. In other words, deferring the load of offscreen images can speed up page load time and time to interactive.
Recomendation: Consider lazy-loading offscreen images to improve page load speed and time to interactive. For more details see: [Lazy loading Images and Video](https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/).

2018-04-26 11:54 UTC, pftg commented
https://cloudinary.com/documentation/responsive_images

2018-04-27 08:14 UTC, pftg commented
Just to confirm that all images and video should be lazyloaded and while they have not been loaded we should use some small placeholders (maybe in small svg or jpeg formats)

- [x] Lazy load use cases images
- [ ] Lazy load video files

2018-04-27 08:21 UTC, pftg commented
and try to not use those extra stuff, just run script to load media after load

2018-04-27 15:01 UTC, andriyParashchuk commented
staging - http://jt-pr271.surge.sh/

2018-04-27 15:03 UTC, andriyParashchuk commented
![1524841366808](https://user-images.githubusercontent.com/23320186/39369577-597a1d2c-4a45-11e8-9dcb-d5397a7e7c61.jpg)

2018-04-27 15:05 UTC, andriyParashchuk commented
@pftg @sweatC  Pls check

2018-04-27 15:21 UTC, sweatC commented
@andriyParashchuk here: 
![image](https://user-images.githubusercontent.com/15202961/39370512-c5da2406-4a47-11e8-9fe0-d4788158c209.png)

2018-04-27 17:53 UTC, andriyParashchuk commented
Lazyload do not work for video with autoplay
![1524851524383](https://user-images.githubusercontent.com/23320186/39377197-0179d2b2-4a5d-11e8-9056-62c367853f3f.jpg)

2018-04-27 17:54 UTC, andriyParashchuk commented
@pftg @sweatC Pls chekc lazyload

2018-04-27 18:06 UTC, sweatC reviewed
Offscreen images have 100% potential savings. Good job!
![image](https://user-images.githubusercontent.com/15202961/39377699-bbbd39b0-4a5e-11e8-9552-addd042a7c08.png)

2018-04-28 14:07 UTC, pftg requested changes
Please check my comments

2018-04-28 14:07 UTC, pftg commented on _assets/javascripts/application.js
> +  document.addEventListener("scroll", lazyLoad);
we need this just after has been loaded page, no need to observe on the scroll. This will produce performance impact.

2018-04-28 14:07 UTC, pftg commented on _includes/sections/main-screen.html
> +    <video playsinline autoplay muted loop preload>
do we need to preload it?

2018-04-28 14:07 UTC, pftg commented on _includes/sections/main-screen.html
> +    <video playsinline autoplay muted loop preload>
I'm ok if it will be loaded a little later

2018-04-28 14:07 UTC, pftg commented on _includes/sections/use-cases.html
> +            <img src="{% asset use-cases_img_01-small.jpg @path %}" data-src="{% asset use-cases_img_01.png @path %}" data-srcset="{% asset use-cases_img_01.png @path %}" class="lazy" alt="Agent Inbo
we do not need to have the placeholder on the first load

2018-04-28 14:07 UTC, pftg commented on _assets/javascripts/application.js
> +  window.addEventListener("orientationchange", lazyLoad);
remove those events, just leave `window.onload` that's all

2018-04-28 14:07 UTC, pftg commented on _assets/javascripts/application.js
> +          if ((lazyImage.getBoundingClientRect().top <= window.innerHeight && lazyImage.getBoundingClientRect().bottom >= 0) && getComputedStyle(lazyImage).display !== "none") {
no need to have this in our case

2018-04-28 14:14 UTC, pftg commented
@andriyParashchuk ![](https://cl.ly/391U2G0c2g0m/Image%202018-04-28%20at%2017.12.36.public.png)

2018-04-28 19:56 UTC, pftg commented on _assets/javascripts/application.js
> +  window.addEventListener("orientationchange", lazyLoad);
got my mistake

2018-04-28 20:05 UTC, merged