Add redirect behavior
jetthoughts/jt.github.io pull request #290
Opened 2018-04-27 17:41 UTC by sweatC

we need to redirect all requests to http://jetthoughts.com/blog/* to https://jtway.co
![image](https://cl.ly/3Y3u321t2J0j/Image%202018-04-12%20at%2020.32.56.public.png)

- Add jekyll-redirect-from gem file.
- Configure gem package.
- Add blog.html redirect.

UPD: Move old post to the Medium. If we don't have this posts on Medium then setup redirect.
![image](https://dzwonsemrish7.cloudfront.net/items/3Z3q0t1l0Y1e3C1E1Y06/Image%202018-05-08%20at%2013.44.37.public.png)

2018-04-27 17:53 UTC, sweatC commented
https://www.useloom.com/share/b4ef352c60a74a0692ab852c6137044a

2018-04-28 14:13 UTC, pftg commented
@sweatC any status for this issue?

2018-04-28 14:15 UTC, pftg commented
@sweatC please deploy

2018-04-30 06:30 UTC, sweatC commented
@pftg deployed: http://jt-pr290.surge.sh/

2018-04-30 09:43 UTC, obliviusm commented
doesn't work on surge
@sweatC is testing on GH pages

2018-04-30 14:56 UTC, obliviusm commented on blog.html
> +  - /blog/tech
is it possible to redirect with wild card `/blog/*` => `https://jtway.co/`

2018-05-02 06:23 UTC, pftg commented on blog.html
> +  - /blog/tech
@obliviusm this plugin does not allow such redirects

2018-05-02 06:26 UTC, pftg commented
@sweatC I see not found for list of pages: https://cl.ly/1H3p2S043P2N/Image%202018-05-02%20at%2009.26.06.public.png

but expected redirect

2018-05-03 19:37 UTC, sweatC commented
@pftg @obliviusm @andriyParashchuk pls check: http://jt-pr290.surge.sh/
Redirect works fine, but we need to change url for gh pages production. For now it's set to staging.
https://www.useloom.com/share/2e42c0d8c16145f098412220cdeb6aea

2018-05-04 07:39 UTC, pftg requested changes
Let's finish all at once

2018-05-04 07:39 UTC, pftg commented on blog.html
> +  - /blog/tech/2010/09/26/installing-pg-gem-on-mac-os.html
I think better to copy all posts from the old blog and left only redirects without any content, and for guys who without js say that blog moved to and new url

2018-05-04 07:44 UTC, pftg commented
@sweatC please move old posts to new blog, update their body to show that we has been moved to jtway.co and new link

2018-05-04 07:46 UTC, pftg commented on bin/production
> +end
1. this is a build, not production cli.
2. no need to use ruby for scripts, will be enough to have bash https://github.com/jetthoughts/jetthoughts.github.io/blob/develop/bin/staging-release

2018-05-04 07:47 UTC, pftg commented on bin/deploy
> +end
1. `bin/release`
2. add build in the script in order to recompile and deploy in one command
3. please use bash

2018-05-04 08:30 UTC, andriyParashchuk commented on redirects/blog.html
> +---
Add new line

2018-05-04 08:30 UTC, andriyParashchuk commented on _config.yml
> +url: http://jt-pr290.surge.sh
You do not need to save the staging url in order to deploy to surge.sh

2018-05-04 12:11 UTC, sweatC commented on _config.yml
> +url: http://jt-pr290.surge.sh
I do this for another purpose. For redirects.

2018-05-04 12:29 UTC, andriyParashchuk commented on _config.yml
> +url: http://jt-pr290.surge.sh
why this url in the PR?
you deploy to surge.sh and forgot the url

2018-05-04 12:45 UTC, sweatC commented on bin/production
> +end
Accepted

2018-05-04 13:08 UTC, sweatC commented on bin/deploy
> +end
Accepted

2018-05-04 13:39 UTC, sweatC commented on _config.yml
> +url: http://jt-pr290.surge.sh
It is only for testing redirects gem.

2018-05-07 12:01 UTC, sweatC commented
@pftg without JS it redirects, and shows document with redirection link, if redirection isn't completed.
https://www.useloom.com/share/65bbcfaa9c5640c784b25b6f970d56af

2018-05-07 14:04 UTC, sweatC commented
Status: Tomorrow will work on adding more articles from archive.

2018-05-08 08:38 UTC, pftg commented
@sweatC what is the status for this issue?

2018-05-08 08:39 UTC, sweatC commented
@pftg it is ready for production

2018-05-08 09:55 UTC, sweatC commented
@pftg pls check

2018-05-08 10:25 UTC, pftg commented
@sweatC please deploy on surge.sh

2018-05-08 11:26 UTC, sweatC commented
@pftg before merging with master I need to change _config.url and rebase all commits.
Staging for verify: http://jt-pr290.surge.sh

2018-05-08 11:38 UTC, pftg commented
@sweatC I tried this https://cl.ly/3w05133e0T1x/Image%202018-05-08%20at%2014.37.21.public.png but have not found any redirects. Could you record gif is it working or not your side

2018-05-08 11:42 UTC, pftg commented
@sweatC looks like is working ![](https://cl.ly/3S281L10083A/Screen%20Recording%202018-05-08%20at%2014.42.gif)

2018-05-08 11:44 UTC, sweatC commented
@pftg pls check
https://www.useloom.com/share/41121dbc450e438bb8ab2cbbd70638e5

2018-05-08 13:04 UTC, pftg commented
@sweatC please squash and reabse

2018-05-08 13:05 UTC, pftg approved these changes
LGTM

2018-05-08 13:45 UTC, sweatC commented
@pftg please merge

2018-05-08 14:23 UTC, obliviusm commented
@sweatC please do rebase instead of merge

2018-05-08 14:57 UTC, merged