[Performance] Load Video for main screen
jetthoughts/jt.github.io pull request #295
Opened 2018-05-02 18:13 UTC by andriyParashchuk

Need load video different quality for a specific device or reduce quality on video

2018-05-02 18:14 UTC, andriyParashchuk commented
Staging - http://jt-pr295.surge.sh/
@pftg @obliviusm @sweatC Pls check

2018-05-03 00:42 UTC, pftg requested changes
Not clear with this solution. Could you clarify your strategy?

2018-05-03 00:42 UTC, pftg commented on _assets/javascripts/application.js
> +  if (window.innerWidth > 1365) {
you could check is it visible or not

2018-05-03 00:42 UTC, pftg commented on _assets/javascripts/application.js
> +videoBg();
why do you need to name this function?

2018-05-03 00:42 UTC, pftg commented on _assets/javascripts/application.js
> +};
what is the purpose of this function? it loads video on html parsed. What is the difference with prev version?

2018-05-03 00:43 UTC, pftg commented on _assets/javascripts/application.js
> +var mainVideo = document.querySelector(".main-video");
why you have not used https://github.com/jetthoughts/jetthoughts.github.io/pull/295/files#diff-2a4fde3d05134dead2ded8c935cda415L171 this style to convert to array?

2018-05-03 00:44 UTC, pftg commented on _includes/sections/main-screen.html
> +      <source src="{% asset video_bg_full_hd.mp4 @path %}" data-src="{% asset video_bg_hd.mp4 @path %}" type="video/mp4">
as I got bg hd should be default, and full hd should be later

2018-05-03 00:47 UTC, pftg commented
@andriyParashchuk I just want to use this https://cl.ly/182t190k2D1q/Image%202018-05-03%20at%2003.45.46.public.png

could you check https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source and without polyfill other browsers

2018-05-03 00:52 UTC, pftg commented on _includes/sections/main-screen.html
> +    <video playsinline autoplay muted loop class="main-video">
![](https://cl.ly/1A080r1F0r2p/Image%202018-05-03%20at%2003.51.51.public.png)

2018-05-03 01:10 UTC, pftg commented
https://rigor.com/blog/2016/03/size-and-quality-optimizations-for-html5-video

2018-05-03 11:54 UTC, andriyParashchuk commented on _includes/sections/main-screen.html
> +    <video playsinline autoplay muted loop class="main-video">
![1525331807673](https://user-images.githubusercontent.com/23320186/39575061-e2e2688a-4ee1-11e8-9762-b2de71beee0a.jpg)

2018-05-03 11:54 UTC, andriyParashchuk commented on _includes/sections/main-screen.html
> +      <source src="{% asset video_bg_full_hd.mp4 @path %}" data-src="{% asset video_bg_hd.mp4 @path %}" type="video/mp4">
Accepted

2018-05-03 11:54 UTC, andriyParashchuk commented on _assets/javascripts/application.js
> +var mainVideo = document.querySelector(".main-video");
Accepted

2018-05-03 11:54 UTC, andriyParashchuk commented on _assets/javascripts/application.js
> +};
This function checks the screen width
If the screen has a width of more than 1366px, the load Full HD video
If the screen has a width of less than 1366px, the load HD video

2018-05-03 11:54 UTC, andriyParashchuk commented on _assets/javascripts/application.js
> +videoBg();
Accepted

2018-05-03 11:54 UTC, andriyParashchuk commented on _assets/javascripts/application.js
> +  if (window.innerWidth > 1365) {
![1525347464387](https://user-images.githubusercontent.com/23320186/39575019-bfaa8f32-4ee1-11e8-91af-8b4f8eb1ab3a.jpg)
![1525347358339](https://user-images.githubusercontent.com/23320186/39575020-bfc442f6-4ee1-11e8-9da1-2df59f5e462a.jpg)

2018-05-03 11:55 UTC, andriyParashchuk commented
this - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source
Attributes size specifies only the width, we set the width of the video and center it in css
Attribute media is what we need, but it only works with <picture> element

2018-05-03 11:57 UTC, andriyParashchuk commented
staging - http://jt-pr295.surge.sh/

2018-05-03 12:43 UTC, andriyParashchuk commented
Clean up js code

2018-05-03 14:41 UTC, pftg approved these changes
LGTM

2018-05-03 14:42 UTC, merged