Upgrade gems
jetthoughts/jt.github.io pull request #296
Opened 2018-05-02 17:03 UTC by pftg

2018-05-02 17:10 UTC, pftg commented
Deployed on https://jt-pr296-pftg.surge.sh

2018-05-03 00:58 UTC, pftg commented
@andriyParashchuk @obliviusm @sweatC please review on http://jt-pr296-pftg.surge.sh/

2018-05-03 16:17 UTC, obliviusm requested changes
@pftg do we need eslint? 
anyway your rules give too much errors in `application.js`

maybe separate pr for linting with lint command and fixed errors?

2018-05-03 16:17 UTC, obliviusm commented on package.json
> +    "surge": "^0.20.1"
👍

2018-05-03 16:17 UTC, obliviusm commented on .eslintrc.js
> +};
no newline

2018-05-03 16:17 UTC, obliviusm commented on .eslintrc.js
> +            4
we use indentation 2

2018-05-04 08:28 UTC, pftg commented
@obliviusm please re-review

2018-05-04 08:52 UTC, obliviusm commented
@pftg 
```
eslint .

/jetthoughts.github.io/_assets/javascripts/application.js
  213:3  error  Parsing error: The keyword 'const' is reserved

/jetthoughts.github.io/_assets/javascripts/form.js
   1:1   error  '$' is not defined                no-undef
   2:21  error  '$' is not defined                no-undef
   3:17  error  '$' is not defined                no-undef
   4:22  error  '$' is not defined                no-undef
  22:23  error  'jsn' is defined but never used   no-unused-vars
  28:24  error  'form' is defined but never used  no-unused-vars
  29:5   error  '$' is not defined                no-undef
  44:16  error  '$' is not defined                no-undef
  51:16  error  '$' is not defined                no-undef
  64:16  error  '$' is not defined                no-undef
  69:5   error  '$el' is not defined              no-undef
  69:41  error  '$' is not defined                no-undef
  69:49  error  '$' is not defined                no-undef
  70:5   error  '$el' is not defined              no-undef
  71:18  error  '$' is not defined                no-undef
  84:16  error  '$' is not defined                no-undef

/jetthoughts.github.io/gulpfile.js
  1:1  error  Parsing error: The keyword 'const' is reserved

✖ 18 problems (18 errors, 0 warnings)

```

2018-05-04 09:01 UTC, pftg commented
let's fix this later

2018-05-04 09:25 UTC, obliviusm commented
@pftg i added few ignores to make linter pass. is it ok?

2018-05-04 09:28 UTC, merged