Set up redirects on nonexistent pages
jetthoughts/jt.github.io pull request #316
Opened 2018-05-21 09:54 UTC by sweatC

Create posts in jtway about nonexistent pages.
Set up redirects on nonexistent pages.
![photo_2018-05-20_11-53-09](https://user-images.githubusercontent.com/15202961/40277268-a3b1f5c2-5c24-11e8-8346-96719799b5c1.jpg)

2018-05-21 09:54 UTC, sweatC commented
@pftg @obliviusm @andriyParashchuk pls check
Staging: http://jt-pr316.surge.sh/
Google Search Console
![image](https://user-images.githubusercontent.com/15202961/40301565-26634b80-5cf5-11e8-8505-c663187da414.png)

2018-05-21 11:35 UTC, andriyParashchuk commented
@sweatC Do you need to redirect internal pages to a blog or homepage?
Because now it's redirected to the blog

2018-05-21 13:26 UTC, pftg commented
@sweatC 

```
- /contact
+  - /career
+  - /credits
+  - /portfolio
+  - /portfolio/mostech
+  - /portfolio/oauth-to-me
+  - /portfolio/coach-alba
+  - /portfolio/greeting-pictures
```

need redirect to https://www.jetthoughts.com/

2018-05-21 13:27 UTC, pftg commented
blog/team/2017/03/20/the-4-steps-to-bring-life-to-a-project -> should be redirected to post on jtway

2018-05-21 13:27 UTC, pftg requested changes
Please check comments

2018-05-21 13:28 UTC, pftg commented
@sweatC please create issue to migrate posts from old blog to jtway if there is usage on GA for last 6 month

2018-05-21 13:36 UTC, pftg commented on blog.html
> +  - /blog/team/2017/03/20/the-4-steps-to-bring-life-to-a-project
Should be redirected to https://jtway.co/the-4-steps-to-bringing-life-to-a-struggling-project-37a53bf9c7dc

2018-05-21 17:11 UTC, sweatC commented on blog.html
> +  - /blog/team/2017/03/20/the-4-steps-to-bring-life-to-a-project
Accepted

2018-05-21 17:19 UTC, sweatC commented
@pftg issue created https://github.com/jetthoughts/jetthoughts.github.io/issues/323.
Redirects fixed.

2018-05-21 17:20 UTC, pftg requested changes
check comments

2018-05-21 17:20 UTC, pftg commented on blog.html
> +  - /portfolio/greeting-pictures
please move them to home.html

2018-05-21 18:39 UTC, sweatC commented on blog.html
> +  - /portfolio/greeting-pictures
Accepted

2018-05-22 11:24 UTC, pftg commented
@sweatC have you added issue to migrate some posts to jtway?

2018-05-22 11:39 UTC, pftg commented
@sweatC please squash commits and ask for merge

2018-05-22 12:18 UTC, sweatC commented
@pftg yes I have added https://github.com/jetthoughts/jetthoughts.github.io/issues/323. Check comment above.
It is ready for merge.

2018-05-22 13:47 UTC, pftg approved these changes
LGTM

2018-05-22 13:47 UTC, merged