Cleanup code
jetthoughts/jt.github.io pull request #371
Opened 2018-11-09 22:21 UTC by andriyParashchuk

Need move all static text to YAML files

2018-11-16 15:08 UTC, obliviusm commented on _data/customers.yml
> +  text: 'Once configured it just works and saves ton of time. Allows you to keep critical data in Airtable and import into google sheets for analytics and calculations. Once configured it just works
can you make it multiline instead of one long line? https://stackoverflow.com/a/21699210

2018-11-16 15:10 UTC, obliviusm requested changes
pls check comment
otherwise good

2018-11-18 15:45 UTC, andriyParashchuk commented
@obliviusm Done

2018-11-23 13:09 UTC, andriyParashchuk commented
@obliviusm please, review again

2018-11-23 13:10 UTC, obliviusm approved these changes
LGTM
pls prepare commits and merge

2018-12-07 22:03 UTC, closed without merging

2018-12-07 22:04 UTC, obliviusm commented
Deployed to https://jetthoughts-pr-371.surge.sh