Remove title from preview
jetthoughts/jt.github.io pull request #396
Opened 2019-04-24 08:33 UTC by sweatC

2019-04-22 15:39 UTC, pftg commented
Also need to add fixes which have been missed in #392 like ![](https://cl.ly/763756/Image%202019-04-22%20at%2018.38.13.png)

2019-04-24 08:29 UTC, sweatC commented
Without company title:
![image](https://user-images.githubusercontent.com/15202961/56644352-30166100-6684-11e9-9fbb-a04e71189a94.png)

2019-04-24 08:57 UTC, sweatC commented
@pftg check: http://jetthoughts-pr396.surge.sh/ on  https://metatags.io/
![image](https://user-images.githubusercontent.com/15202961/56646399-27c02500-6688-11e9-9cdb-afab21edf2a3.png)

2019-04-24 11:12 UTC, pftg commented
@sweatC https://github.com/jetthoughts/jetthoughts.github.io/pull/396#issuecomment-485453094 have not been fixed, what are you going to do with it?

2019-04-24 11:50 UTC, sweatC commented
Fixed twitter meta tag for title: http://jetthoughts-pr-396.surge.sh/

2019-04-24 21:33 UTC, ad-sys commented
LGTM, but checked twitter when posted link and no preview for some reason.
Also checked https://cards-dev.twitter.com/ and looks good

2019-04-25 06:06 UTC, pftg commented on _includes/head.html
> +  <meta name="twitter:text:title" content="{{ site.title }}"/>
we need to have 2 titles one per agent inbox page and one per home page. could you support this too?

2019-04-25 06:11 UTC, pftg requested changes
Check my comments

2019-04-25 06:11 UTC, pftg commented on _includes/head.html
> +  <meta name="twitter:text:title" content="{{ site.title }}"/>
Better to fix in this issue:

- [ ] og:title
- [ ] make different titles for agentinbox case page (find the best fit page title) and for home page

2019-04-25 08:40 UTC, sweatC commented on _includes/head.html
> +  <meta name="twitter:text:title" content="{{ site.title }}"/>
@pftg pls provide a title and description for agent inbox. Also, there is a task which will fix it: https://github.com/jetthoughts/jetthoughts.github.io/issues/398

2019-04-25 08:53 UTC, pftg commented on _includes/head.html
> +  <meta name="twitter:text:title" content="{{ site.title }}"/>
@sweatC will be great to see your suggestions, also you could discuss with @andriyParashchuk and @ad-sys what is the best

2019-04-25 09:54 UTC, andriyParashchuk reviewed
LGTM

2019-04-25 11:09 UTC, andriyParashchuk commented on _includes/head.html
> +  <meta name="twitter:text:title" content="{{ site.title }}"/>
Will fix in #398 
@sweatC No need change `page.title`. In #398 we will use `page.title` and `page.deskription` for each page

2019-04-25 11:25 UTC, sweatC commented on _includes/head.html
> +  <meta name="twitter:text:title" content="{{ site.title }}"/>
@andriyParashchuk removed last change.

2019-04-25 11:26 UTC, pftg approved these changes

2019-04-25 11:26 UTC, merged